version: "3"

services:
  java:
    container_name: java_dev_container
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ../
        target: /workspace:cached
    tty: true